language: r
r:
  - release
  - devel
  - bioc-release

sudo: false
cran: https://cran.rstudio.com

cache:
  packages: true
apt_packages: libnetcdf-dev

env:
  global:
    - NOT_CRAN: true
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
