language: r
r:
  - bioc-release

sudo: required
cran: https://cran.rstudio.com

r_packages:
  - devtools
cache:
  packages: true
apt_packages: 
  - libnetcdf-dev
  - netcdf-bin
  - libmagick++-dev
env:
  global:
    - NOT_CRAN: true
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
